language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28
    - android-18
    - sys-img-armeabi-v7a-android-18

before_install:
- chmod +x gradlew
- gem update --system
- gem install bundler
- bundle install

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &