env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - EMU_FLAVOR=default
  - ANDROID_HOME=/usr/local/android-sdk
  - TOOLS=${ANDROID_HOME}/tools
  - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  - API=27
  - ABI=x86_64
  - AUDIO=-no-audio
language: android
dist: trusty
android:
  components:
  - tools
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_d16e002e72d4_key -iv $encrypted_d16e002e72d4_iv
  -in api-bird-monitor.json.enc -out api-bird-monitor.json -d
- chmod +x gradlew
- gem update --system
- gem install bundler
- bundle install
- echo 'count=0' > /home/travis/.android/repositories.cfg
- echo y | sdkmanager "platform-tools" >/dev/null
- echo y | sdkmanager "tools" >/dev/null
- echo y | sdkmanager "build-tools;28.0.3" >/dev/null
- echo y | sdkmanager "platforms;android-$API" >/dev/null
- echo y | sdkmanager "platforms;android-28" >/dev/null
- echo y | sdkmanager --channel=4 "emulator"
- echo y | sdkmanager "extras;android;m2repository" >/dev/null
- echo y | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI"
- echo no | avdmanager create avd  --device "Nexus 6P" --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI"
  -c 10M
- emulator -verbose -avd test -no-accel -no-snapshot -no-window $AUDIO -camera-back
  none -camera-front none -selinux permissive -qemu -m 2048 &
- android-wait-for-emulator
- adb shell input keyevent 82 &
# install:
# - true
# script:
# - "./gradlew build"
