env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - EMU_FLAVOR=default
  - ANDROID_HOME=/usr/local/android-sdk
  - TOOLS=${ANDROID_HOME}/tools
  - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  - API=28
  - ABI=x86
  - AUDIO=-no-audio
language: android
dist: trusty
android:
  components:
  - tools
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- chmod +x gradlew
- gem update --system
- gem install bundler
- bundle install
- echo 'count=0' > /home/travis/.android/repositories.cfg
- echo y | sdkmanager "platform-tools" >/dev/null
- echo y | sdkmanager "tools" >/dev/null
- echo y | sdkmanager "build-tools;28.0.3" >/dev/null
- echo y | sdkmanager "platforms;android-$API" >/dev/null
- echo y | sdkmanager --channel=4 "emulator"
- echo y | sdkmanager "extras;android;m2repository" >/dev/null
script:
- "./gradlew clean assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: KDvYoMsfkgL5tVwm6X0QLlx3GLPKOH/24Jeajc1aB1ctfZ6sWX3ZQoJ+gObuIiZ3uIEenzT0Jp4mQYcKEJeCB3SqDx1PvXp4+473HolYxbJiY+h/BJCLaAp/BsOyyAxEq4eskP2w2fSdtQXyjyr1BvQEjbOlQFUCENRFww1TSSPgIdxeIfTb1cK7hHHexfuqCLbzboKz1kfG73I4G31zH9N/HksLeLbCZCQwG4rFCcjFtgsPI7o6ONToO6KZnm4AZ3dPcLhtYjU3DFZq7wQ8dp5o1evJd/c80fB7aRhv0zHz+Wj2mp+g2sb2RsL0OviiGjtL9xnRGlM6bBHnCkLEHLxXO2fvDTf83LZZpUVOlTGwuJ7Mtr5PbtvGYN2/Wa87T7sguZSGzujv4hzHRxvjBo+oMJTdxzGugMi9z55i7WmvfFMaPH6cBYSzOWhqxIs8sBxKiQlT1Q73dgH3MxF8fO4SDJYhHN6XP1UglFWJAyJZrw7OWftCnOggJ4ndPP5WkuySiDdNnS8W0kmMz2oGQHKbVonA1Zfk45RbJ/D4C+PsT5oBMtLfBKijH1SdD8RPQBMaH+osnarFWj7XD0GZ0+3HYkBDgCYYmpWy+BevlQe9KJflzE2G1eLXt+C8mGUIwhInOQN1BqkK00ZpnAbDPq1v4fpNswZ/Gf6RMkM++io=
  file: 'app/build/outputs/apk/release/*.apk'
