env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - EMU_FLAVOR=default
  - ANDROID_HOME=/usr/local/android-sdk
  - TOOLS=${ANDROID_HOME}/tools
  - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  - API=27
  - ABI=x86
  - AUDIO=-no-audio
language: android
dist: trusty
android:
  components:
  - tools
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- chmod +x gradlew
- gem update --system
- gem install bundler
- bundle install
- echo 'count=0' > /home/travis/.android/repositories.cfg
- echo y | sdkmanager "platform-tools" >/dev/null
- echo y | sdkmanager "tools" >/dev/null
- echo y | sdkmanager "build-tools;28.0.3" >/dev/null
- echo y | sdkmanager "platforms;android-$API" >/dev/null
- echo y | sdkmanager "platforms;android-28" >/dev/null
- echo y | sdkmanager --channel=4 "emulator"
- echo y | sdkmanager "extras;android;m2repository" >/dev/null
script:
- "./gradlew clean build"

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: k/nJWju6Jjgk/yJ4N1mt4bzJ2v7aVVcDQt6dOP54mlbX39vXau4pg/4BNxdkrM0Sl46sd262NBipN4QZWPwkKNldihSDxYXr3XReW7jmXgEbqd9/jaAXiMBVICvOyaVgtlAv6HaUW4/3jceKrt6WWvThHdHJmYLXpAXEWUYo7eoQtNIz2PQa3fEVFQYXAiyg+nZjvkzdUCSxK6gOqFl/1B6Y9aApaFkFKbZvmM1u2sw1aSJBLWnUGp6lE1//WUzQiRKFIDJqplxUtLXaVSvefl1KLEwxE+TRi2gv6K06GJHFnsG0BAo45WPoluLr4ixt1UDSHrUQaNzfJMufVBHtt8j22vFxMEqI45c9OZina+nGRckp+vHDTBGR3shP6XTstSsWkRdqER+of7b6Heaq/Z+MW74bTLOnn9w9b9kDglnpUjnGlB6/auWShoyzMZ0crmTdvyNwfONJGh0SU/pAJxDi+4WRAuy6ldCbGmaJGXdVeLI1b+zoW0huu+VDIMgajd+zxTlkWPnWz0FMEnAbOnwd0lcllulmqnwzX1kmR22fnNc38M49tVXa+ccs/QBCwPmmYW5mo2u65xUBaeZsgqWODptHiEGaF8dj+zxqyHInm7Ci8nvgIG94ZpGCGB/9RoZAuSzHof14OXTUhCr5orrjEclvdoYAjqPrZikZVUA=
  file: "app/build/outputs/apk/release/*"
  on:
    repo: gferraro/bird-monitor
