# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  # desc "Builds a new Alpha release on Google Play"
  # lane :alpha do
  #   # ...
  #   gradle(
  #     task: 'assemble',
  #     build_type: 'Debug'
  #   )

  # end

  # desc "Deploys a new Alpha release on Google Play"
  # lane :playstore_alpha do
  #   # ...
  #   gradle(
  #     task: 'assemble',
  #     build_type: 'Debug'
  #   )
  #   upload_to_play_store(
  #     track: 'alpha',
  #   )
  # end
end
# http://tigar.nl/2018/05/15/android-app-signing/ can be used in future
